// gRPC-Web implementation of MetricsService.
//
// Replaces metrics_service.dart once CI generates the protobuf stubs.
// Usage: in status_screen.dart, swap the import to this file.
//
// To activate:
//   1. Run CI (or locally: protoc --dart_out=grpc:lib/src/generated shared.proto)
//   2. Replace `metrics_service.dart` import with `metrics_grpc_service.dart`
//   3. Remove the http: dependency from pubspec.yaml
//
// ignore_for_file: unused_import
library;

import 'package:grpc/grpc_web.dart';

// Stubs are generated by CI into lib/src/generated/ (.gitignored).
// Uncomment after first CI run or local protoc generation:
//
// import '../src/generated/shared.pb.dart';
// import '../src/generated/shared.pbgrpc.dart';
// import '../models/metrics_model.dart';
//
// class MetricsGrpcService {
//   late final MetricsServiceClient _client;
//
//   MetricsGrpcService() {
//     // Same origin — no hard-coded URL.
//     final channel = GrpcWebClientChannel.xhr(Uri.base);
//     _client = MetricsServiceClient(channel);
//   }
//
//   Future<MetricsModel> fetchMetrics() async {
//     final res = await _client.getMetrics(GetMetricsRequest());
//     return MetricsModel.fromProto(res);
//   }
//
//   Stream<MetricsModel> streamMetrics() {
//     return _client
//         .streamMetrics(GetMetricsRequest())
//         .map(MetricsModel.fromProto);
//   }
// }
